### ISSUE TITLE
运行一段时间后cpu占用异常

### ISSUE THREAD

**Issue by yongman** [Auska/docker-rrshareweb#5]
**运行环境：**
群晖的docker环境。

**现象：**
运行两天后，下载了有几十集美剧，当所有任务完成后，并且没有任何下载和上传流量，cpu占用一直维持在30%左右，重启后恢复。不知道大家有没有遇到过？

**Comment by wentijianihao** [comment]
同样的问题，CPU占用偏高，没有上传下载任务时也降不下来。  对比群晖里其他运行中的容器，这一情况很明显。

**Comment by shuncox** [comment]
同样的问题，CPU占用一直保持100%+

**Comment by Explorer1092** [comment]
同样的问题，CPU占用一直保持100%+

**Comment by Auska** [comment]
这个问题你们反应错地方了 [http://app.rrys.tv/](反馈地址)使用的Linux版本
这本身就是挖矿的程序 当然会占用CPU
可以尝试用其它手段限制CPU占用
我目前使用cpus限制CPU占用

**Comment by jianhuiz** [comment]
挖矿？有消息来源吗？
感觉好像cpu占用是缓慢上升的，我一直是以为go routine泄漏，或者别的什么资源泄漏

**Comment by Auska** [comment]
要不然人人钻 和 CVN 哪来的
